-- Admin invite tokens: generated by admins, used in /admin-join?token=xxx
create table if not exists public.admin_invite_tokens (
  id uuid primary key default gen_random_uuid(),
  token text not null unique,
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz
);

-- Admin approval requests: when someone uses invite link, request is created; approver (e.g. leokimandula) approves
create table if not exists public.admin_approval_requests (
  id uuid primary key default gen_random_uuid(),
  token text not null,
  requested_by uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  unique(token, requested_by)
);

-- Calendar events: scope 'general' (all schools) or 'schools' (selected via calendar_event_schools)
create table if not exists public.calendar_events (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  event_date date not null,
  event_end_date date,
  scope text not null default 'general' check (scope in ('general', 'schools')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.calendar_event_schools (
  event_id uuid not null references public.calendar_events(id) on delete cascade,
  school_id uuid not null references public.schools(id) on delete cascade,
  primary key (event_id, school_id)
);

-- Important information / notices: same scope pattern
create table if not exists public.notices (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  body text not null,
  scope text not null default 'general' check (scope in ('general', 'schools')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.notice_schools (
  notice_id uuid not null references public.notices(id) on delete cascade,
  school_id uuid not null references public.schools(id) on delete cascade,
  primary key (notice_id, school_id)
);

alter table public.admin_invite_tokens enable row level security;
alter table public.admin_approval_requests enable row level security;
alter table public.calendar_events enable row level security;
alter table public.calendar_event_schools enable row level security;
alter table public.notices enable row level security;
alter table public.notice_schools enable row level security;

-- Only service role / admin APIs manage these (no public RLS policies)
-- Reads for portal: service role fetches events/notices filtered by school
